# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ADataFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('date2str', models.CharField(max_length=10)),
                ('associationrules', models.CharField(max_length=60)),
                ('confidence', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='FDataFrame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('date2str', models.CharField(max_length=10)),
                ('frequentitems', models.CharField(max_length=50)),
                ('support', models.FloatField()),
            ],
        ),
    ]
