# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 03:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='adataframe',
            name='confidence_threshold',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adataframe',
            name='support_threshold',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fdataframe',
            name='confidence_threshold',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='fdataframe',
            name='support_threshold',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
